export const career = [
  ['2026', 'Abu Sarhad', 'IT Supervisor', 'مشرف تقنية المعلومات'],
  ['2025', 'Saql Education', 'IT Support Specialist', 'أخصائي دعم تقنية المعلومات'],
  ['2024', 'Alamthl · Jeddah', 'System Development', 'تطوير الأنظمة'],
  ['2019–2023', 'Wise School', 'IT Director · School ERP in C#', 'مدير تقنية المعلومات · تطوير نظام المدرسة بلغة C#'],
  ['2017–2018', 'Afrestar Logistics · Dubai', 'Logistics sector experience', 'خبرة في قطاع الخدمات اللوجستية'],
  ['2016', 'Adama Youth Academy', 'System Analyst & Developer · PHP', 'محلل ومطور أنظمة · PHP'],
  ['2015', 'Saudi Printing & Packaging', 'Internship · ERP Support & Help Desk', 'تدريب عملي · دعم ERP ومكتب المساعدة'],
  ['2012–2014', 'Badr Printing Press', 'System Analyst & Graphic Designer', 'محلل أنظمة ومصمم جرافيك'],
];
export const content = {
  en: {
    name: 'Ibrahim Khalid', pageTitle: 'Ibrahim Khalid | Software, IT & Design', description: 'Ibrahim Khalid, IT Supervisor and software developer in Jeddah. Explore ERP development, IT support, systems analysis and graphic design experience.', skip: 'Skip to content', navigation: 'Main navigation', openMenu: 'Open menu', closeMenu: 'Close menu', nav: [['About', 'about'], ['Expertise', 'skills'], ['Work', 'projects'], ['Experience', 'experience']], letsTalk: 'Let’s talk', status: 'OPEN TO OPPORTUNITIES & PROJECTS', hero: ['Practical systems.', 'Thoughtful design.', 'Better business.'], intro: 'I’m Ibrahim, an IT Supervisor, software developer and designer. I help organizations simplify their operations, support their people and bring ideas to life.', viewWork: 'Explore my work', download: 'Download CV', location: 'Jeddah, Saudi Arabia', languages: 'Arabic · English · Amharic', since: 'Career began', coreTools: 'Core development tools', sectorsValue: 'Education · Logistics · Print', sectors: 'Experience across industries', aboutLabel: 'THE PERSON BEHIND THE WORK', aboutTitle: 'A technical mind.\nA creative perspective.', aboutText: 'My experience connects software development, systems analysis, IT operations and visual communication. I understand both the systems a business needs and the people who use them.', aboutExtra: 'From building a school ERP in C# to supporting educational platforms and creating graphic design, I bring hands-on experience across Saudi Arabia, Ethiopia and Dubai.', degree: 'Bachelor of Information Technologies', university: 'Software Engineering · Adama Science and Technology University · 2016', skillsLabel: 'WHAT I BRING', skillsTitle: 'One partner. Three perspectives.', skillsIntro: 'Development, operational support and creative communication working together.', expertise: [
      {title: 'Software & systems', text: 'Custom applications built around real operational needs, from desktop tools to educational management systems.', skills: ['C#', 'PHP', 'Java', 'C++', 'JavaScript', 'MySQL', 'ERP']},
      {title: 'IT support & operations', text: 'Reliable support for users, networks and business platforms, informed by IT leadership experience.', skills: ['IT Support', 'Networking', 'Windows Server', 'Troubleshooting', 'Systems Analysis']},
      {title: 'Design & digital marketing', text: 'Clear visual identities, print materials and digital content that help businesses communicate.', skills: ['Graphic Design', 'Brand Identity', 'Social Media', 'SEO', 'Digital Marketing']},
    ], workLabel: 'SELECTED EXPERIENCE', workTitle: 'Built around real needs.', workIntro: 'A selection of the systems I’ve developed across education and printing.', filterLabel: 'Filter projects', filters: [['all', 'All projects'], ['education', 'Education'], ['business', 'Business tools']], projects: [
      {id: 1, type: 'education', category: 'EDUCATION / ERP', year: '2019–2023', title: 'School ERP', text: 'Developed a school ERP in C# during my work as IT Director at Wise School, bringing school operations into a custom management system.', tools: ['C#', 'ERP', 'Systems Analysis']},
      {id: 2, type: 'education', category: 'EDUCATION / WEB', year: '2016', title: 'Academy management system', text: 'Developed a PHP management system for Adama Youth Academy as a system analyst and developer.', tools: ['PHP', 'Management Systems', 'Web Development']},
      {id: 3, type: 'business', category: 'PRINT / BUSINESS TOOLS', year: '2012–2014', title: 'Estimation & quotation tools', text: 'Developed a C++ cost estimation application and Java quotation tools for Badr Printing Press, alongside graphic design work.', tools: ['C++', 'Java', 'Cost Estimation']},
    ], projectNote: 'Illustrative visuals. Project details describe my professional experience; client systems are not public demos.', experienceLabel: 'PROFESSIONAL JOURNEY', experienceTitle: 'Experience that connects the dots.', experienceIntro: 'A career across education, logistics, printing and corporate technology.', servicesLabel: 'HOW I CAN HELP', servicesTitle: 'Let’s put your next idea to work.', servicesIntro: 'Practical support for businesses, schools and growing teams.', services: [['Custom software', 'Web and desktop applications, ERP systems and workflow tools.'], ['IT support & consulting', 'User support, networking, troubleshooting and systems analysis.'], ['Graphic design', 'Brand identities, print materials and social media designs.'], ['Digital marketing', 'Content planning, SEO and digital campaign support.']], contactLabel: 'START A CONVERSATION', contactTitle: 'Have a role or project', contactAccent: 'in mind?', contactIntro: 'Tell me what you’re working on. Let’s explore how my experience can help.', email: 'EMAIL', ksaPhone: 'SAUDI ARABIA', ethPhone: 'ETHIOPIA', copyEmail: 'Copy email address', copied: 'Email copied', footer: 'Technology with a creative perspective.', backTop: 'Back to top',
  },
  ar: {
    name: 'إبراهيم خالد', pageTitle: 'إبراهيم خالد | تطوير البرمجيات وتقنية المعلومات والتصميم', description: 'إبراهيم خالد، مشرف تقنية المعلومات ومطور برمجيات في جدة. خبرة في تطوير أنظمة ERP والدعم التقني وتحليل النظم والتصميم الجرافيكي.', skip: 'انتقل إلى المحتوى', navigation: 'التنقل الرئيسي', openMenu: 'فتح القائمة', closeMenu: 'إغلاق القائمة', nav: [['نبذة عني', 'about'], ['مهاراتي', 'skills'], ['أعمالي', 'projects'], ['خبراتي', 'experience']], letsTalk: 'تواصل معي', status: 'متاح للفرص المهنية والمشاريع', hero: ['أنظمة عملية.', 'تصميم مدروس.', 'أعمال أكثر كفاءة.'], intro: 'أنا إبراهيم، مشرف تقنية المعلومات ومطور برمجيات ومصمم. أساعد المؤسسات على تبسيط عملياتها، ودعم فرقها، وتحويل الأفكار إلى حلول عملية.', viewWork: 'استعرض أعمالي', download: 'تحميل السيرة الذاتية', location: 'جدة، المملكة العربية السعودية', languages: 'العربية · الإنجليزية · الأمهرية', since: 'بداية المسار المهني', coreTools: 'أدوات التطوير الأساسية', sectorsValue: 'التعليم · اللوجستيات · الطباعة', sectors: 'خبرة في قطاعات متنوعة', aboutLabel: 'الشخص وراء العمل', aboutTitle: 'تفكير تقني.\nورؤية إبداعية.', aboutText: 'تجمع خبرتي بين تطوير البرمجيات، وتحليل الأنظمة، وتشغيل تقنية المعلومات، والتواصل البصري. أفهم الأنظمة التي تحتاجها المؤسسة، والأشخاص الذين يستخدمونها.', aboutExtra: 'من تطوير نظام مدرسة بلغة C# إلى دعم المنصات التعليمية والتصميم الجرافيكي، أقدّم خبرة عملية اكتسبتها في السعودية وإثيوبيا ودبي.', degree: 'بكالوريوس تقنية المعلومات', university: 'هندسة البرمجيات · جامعة أداما للعلوم والتكنولوجيا · 2016', skillsLabel: 'ما أقدّمه', skillsTitle: 'خبرة واحدة. ثلاث زوايا.', skillsIntro: 'تطوير البرمجيات والدعم التشغيلي والتواصل الإبداعي ضمن رؤية متكاملة.', expertise: [
      {title: 'البرمجيات والأنظمة', text: 'تطبيقات مخصصة للاحتياجات التشغيلية، من أدوات سطح المكتب إلى أنظمة إدارة المؤسسات التعليمية.', skills: ['C#', 'PHP', 'Java', 'C++', 'JavaScript', 'MySQL', 'ERP']},
      {title: 'الدعم والتشغيل التقني', text: 'دعم المستخدمين والشبكات ومنصات العمل، بالاستفادة من خبرتي في إدارة تقنية المعلومات.', skills: ['الدعم التقني', 'الشبكات', 'Windows Server', 'حل المشكلات', 'تحليل الأنظمة']},
      {title: 'التصميم والتسويق الرقمي', text: 'هويات بصرية واضحة ومواد مطبوعة ومحتوى رقمي يساعد المؤسسات على إيصال رسالتها.', skills: ['التصميم الجرافيكي', 'الهوية البصرية', 'التواصل الاجتماعي', 'SEO', 'التسويق الرقمي']},
    ], workLabel: 'أعمال مختارة', workTitle: 'حلول لاحتياجات حقيقية.', workIntro: 'نماذج من الأنظمة التي طورتها في قطاعي التعليم والطباعة.', filterLabel: 'تصفية المشاريع', filters: [['all', 'جميع المشاريع'], ['education', 'التعليم'], ['business', 'أدوات الأعمال']], projects: [
      {id: 1, type: 'education', category: 'التعليم / ERP', year: '2019–2023', title: 'نظام إدارة المدرسة', text: 'طورت نظام ERP للمدرسة بلغة C# خلال عملي مديرًا لتقنية المعلومات في Wise School، ضمن نظام إدارة مخصص لعمليات المدرسة.', tools: ['C#', 'ERP', 'تحليل الأنظمة']},
      {id: 2, type: 'education', category: 'التعليم / الويب', year: '2016', title: 'نظام إدارة الأكاديمية', text: 'طورت نظام إدارة باستخدام PHP لأكاديمية Adama Youth Academy خلال عملي محللًا ومطورًا للأنظمة.', tools: ['PHP', 'أنظمة الإدارة', 'تطوير الويب']},
      {id: 3, type: 'business', category: 'الطباعة / أدوات الأعمال', year: '2012–2014', title: 'أدوات تقدير التكلفة وعروض الأسعار', text: 'طورت تطبيقًا لتقدير التكلفة باستخدام C++ وأدوات عروض أسعار باستخدام Java في مطبعة بدر، إلى جانب أعمال التصميم الجرافيكي.', tools: ['C++', 'Java', 'تقدير التكلفة']},
    ], projectNote: 'الرسومات توضيحية. تصف المشاريع خبرتي المهنية، وأنظمة العملاء ليست عروضًا عامة متاحة للتجربة.', experienceLabel: 'المسار المهني', experienceTitle: 'خبرة تربط مختلف الجوانب.', experienceIntro: 'مسيرة في التعليم والخدمات اللوجستية والطباعة وتقنية المعلومات.', servicesLabel: 'كيف أساعدك', servicesTitle: 'لنحوّل فكرتك إلى عمل.', servicesIntro: 'حلول عملية للشركات والمدارس وفرق العمل.', services: [['تطوير البرمجيات', 'تطبيقات الويب وسطح المكتب وأنظمة ERP وأدوات سير العمل.'], ['الدعم والاستشارات التقنية', 'دعم المستخدمين والشبكات وحل المشكلات وتحليل الأنظمة.'], ['التصميم الجرافيكي', 'الهويات البصرية والمطبوعات وتصاميم التواصل الاجتماعي.'], ['التسويق الرقمي', 'تخطيط المحتوى وتحسين محركات البحث ودعم الحملات الرقمية.']], contactLabel: 'لنبدأ الحديث', contactTitle: 'لديك فرصة أو مشروع', contactAccent: 'تريد تطويره؟', contactIntro: 'أخبرني بما تعمل عليه، ولنتحدث عن كيفية الاستفادة من خبرتي.', email: 'البريد الإلكتروني', ksaPhone: 'المملكة العربية السعودية', ethPhone: 'إثيوبيا', copyEmail: 'نسخ البريد الإلكتروني', copied: 'تم نسخ البريد', footer: 'خبرة تقنية برؤية إبداعية.', backTop: 'العودة للأعلى',
  },
};
